code --install-extension EliverLara.andromeda
code --install-extension Kal.theme-glacier
code --install-extension SolarLiner.linux-themes
code --install-extension ahsanayaz.vscode-ngrx-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension benjaminBlonde.monokai-alt
code --install-extension brunomartens.bma-coverage
code --install-extension christian-kohler.path-intellisense
code --install-extension davidbabel.vscode-simpler-icons
code --install-extension eg2.tslint
code --install-extension GrapeCity.gc-excelviewer
code --install-extension HookyQR.beautify
code --install-extension ionutvmi.path-autocomplete
code --install-extension jithurjacob.nbpreviewer
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-csscomb
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-python.python
code --install-extension ms-toolsai.vscode-ai
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.PowerShell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension PeterJausovec.vscode-docker
code --install-extension Pivotal.vscode-spring-boot
code --install-extension PKief.material-icon-theme
code --install-extension quangogage.quango-calm
code --install-extension redhat.java
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension secanis.jenkinsfile-support
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension zhuangtongfa.Material-theme
